//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CalcPrecoPrazoWSSoap")]
    public interface CalcPrecoPrazoWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoPrazo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrecoPrazoResponse CalcPrecoPrazo(ServiceReference1.CalcPrecoPrazoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoPrazo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrecoPrazoResponse> CalcPrecoPrazoAsync(ServiceReference1.CalcPrecoPrazoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoPrazoData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrecoPrazoDataResponse CalcPrecoPrazoData(ServiceReference1.CalcPrecoPrazoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoPrazoData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrecoPrazoDataResponse> CalcPrecoPrazoDataAsync(ServiceReference1.CalcPrecoPrazoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoPrazoRestricao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrecoPrazoRestricaoResponse CalcPrecoPrazoRestricao(ServiceReference1.CalcPrecoPrazoRestricaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoPrazoRestricao", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrecoPrazoRestricaoResponse> CalcPrecoPrazoRestricaoAsync(ServiceReference1.CalcPrecoPrazoRestricaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPreco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrecoResponse CalcPreco(ServiceReference1.CalcPrecoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPreco", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrecoResponse> CalcPrecoAsync(ServiceReference1.CalcPrecoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrecoDataResponse CalcPrecoData(ServiceReference1.CalcPrecoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrecoDataResponse> CalcPrecoDataAsync(ServiceReference1.CalcPrecoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrazo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrazoResponse CalcPrazo(ServiceReference1.CalcPrazoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrazo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrazoResponse> CalcPrazoAsync(ServiceReference1.CalcPrazoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrazoData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrazoDataResponse CalcPrazoData(ServiceReference1.CalcPrazoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrazoData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrazoDataResponse> CalcPrazoDataAsync(ServiceReference1.CalcPrazoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrazoRestricao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrazoRestricaoResponse CalcPrazoRestricao(ServiceReference1.CalcPrazoRestricaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrazoRestricao", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrazoRestricaoResponse> CalcPrazoRestricaoAsync(ServiceReference1.CalcPrazoRestricaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoFAC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcPrecoFACResponse CalcPrecoFAC(ServiceReference1.CalcPrecoFACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcPrecoFAC", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcPrecoFACResponse> CalcPrecoFACAsync(ServiceReference1.CalcPrecoFACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcDataMaxima", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.CalcDataMaximaResponse CalcDataMaxima(ServiceReference1.CalcDataMaximaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcDataMaxima", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CalcDataMaximaResponse> CalcDataMaximaAsync(ServiceReference1.CalcDataMaximaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaServicos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.ListaServicosResponse ListaServicos(ServiceReference1.ListaServicosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaServicos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListaServicosResponse> ListaServicosAsync(ServiceReference1.ListaServicosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaServicosSTAR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.ListaServicosSTARResponse ListaServicosSTAR(ServiceReference1.ListaServicosSTARRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaServicosSTAR", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListaServicosSTARResponse> ListaServicosSTARAsync(ServiceReference1.ListaServicosSTARRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificaModal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.VerificaModalResponse VerificaModal(ServiceReference1.VerificaModalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificaModal", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.VerificaModalResponse> VerificaModalAsync(ServiceReference1.VerificaModalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVersao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.getVersaoResponse getVersao(ServiceReference1.getVersaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVersao", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getVersaoResponse> getVersaoAsync(ServiceReference1.getVersaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calcPrazoNovo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.calcPrazoNovoResponse calcPrazoNovo(ServiceReference1.calcPrazoNovoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calcPrazoNovo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.calcPrazoNovoResponse> calcPrazoNovoAsync(ServiceReference1.calcPrazoNovoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cResultado
    {
        
        private cServico[] servicosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public cServico[] Servicos
        {
            get
            {
                return this.servicosField;
            }
            set
            {
                this.servicosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cServico
    {
        
        private int codigoField;
        
        private string valorField;
        
        private string prazoEntregaField;
        
        private string valorMaoPropriaField;
        
        private string valorAvisoRecebimentoField;
        
        private string valorValorDeclaradoField;
        
        private string entregaDomiciliarField;
        
        private string entregaSabadoField;
        
        private string erroField;
        
        private string msgErroField;
        
        private string valorSemAdicionaisField;
        
        private string obsFimField;
        
        private string dataMaxEntregaField;
        
        private string horaMaxEntregaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrazoEntrega
        {
            get
            {
                return this.prazoEntregaField;
            }
            set
            {
                this.prazoEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ValorMaoPropria
        {
            get
            {
                return this.valorMaoPropriaField;
            }
            set
            {
                this.valorMaoPropriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ValorAvisoRecebimento
        {
            get
            {
                return this.valorAvisoRecebimentoField;
            }
            set
            {
                this.valorAvisoRecebimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ValorValorDeclarado
        {
            get
            {
                return this.valorValorDeclaradoField;
            }
            set
            {
                this.valorValorDeclaradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EntregaDomiciliar
        {
            get
            {
                return this.entregaDomiciliarField;
            }
            set
            {
                this.entregaDomiciliarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EntregaSabado
        {
            get
            {
                return this.entregaSabadoField;
            }
            set
            {
                this.entregaSabadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MsgErro
        {
            get
            {
                return this.msgErroField;
            }
            set
            {
                this.msgErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ValorSemAdicionais
        {
            get
            {
                return this.valorSemAdicionaisField;
            }
            set
            {
                this.valorSemAdicionaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string obsFim
        {
            get
            {
                return this.obsFimField;
            }
            set
            {
                this.obsFimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DataMaxEntrega
        {
            get
            {
                return this.dataMaxEntregaField;
            }
            set
            {
                this.dataMaxEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string HoraMaxEntrega
        {
            get
            {
                return this.horaMaxEntregaField;
            }
            set
            {
                this.horaMaxEntregaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class versao
    {
        
        private string versaoAtualField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string versaoAtual
        {
            get
            {
                return this.versaoAtualField;
            }
            set
            {
                this.versaoAtualField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cModal
    {
        
        private string codigoField;
        
        private string modalField;
        
        private string obsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string modal
        {
            get
            {
                return this.modalField;
            }
            set
            {
                this.modalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string obs
        {
            get
            {
                return this.obsField;
            }
            set
            {
                this.obsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cResultadoModal
    {
        
        private cModal[] servicosModalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public cModal[] ServicosModal
        {
            get
            {
                return this.servicosModalField;
            }
            set
            {
                this.servicosModalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cServicosCalculo
    {
        
        private string codigoField;
        
        private string descricaoField;
        
        private string calcula_precoField;
        
        private string calcula_prazoField;
        
        private string erroField;
        
        private string msgErroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string calcula_preco
        {
            get
            {
                return this.calcula_precoField;
            }
            set
            {
                this.calcula_precoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string calcula_prazo
        {
            get
            {
                return this.calcula_prazoField;
            }
            set
            {
                this.calcula_prazoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string msgErro
        {
            get
            {
                return this.msgErroField;
            }
            set
            {
                this.msgErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cResultadoServicos
    {
        
        private cServicosCalculo[] servicosCalculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public cServicosCalculo[] ServicosCalculo
        {
            get
            {
                return this.servicosCalculoField;
            }
            set
            {
                this.servicosCalculoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cObjeto
    {
        
        private string codigoField;
        
        private string servicoField;
        
        private string cepOrigemField;
        
        private string cepDestinoField;
        
        private int prazoEntregaField;
        
        private string dataPostagemField;
        
        private string dataPostagemCalculoField;
        
        private string dataMaxEntregaField;
        
        private string postagemDHField;
        
        private string dataUltimoEventoField;
        
        private string codigoUltimoEventoField;
        
        private string tipoUltimoEventoField;
        
        private string descricaoUltimoEventoField;
        
        private string erroField;
        
        private string msgErroField;
        
        private string nuTicketField;
        
        private string formaPagamentoField;
        
        private string valorPagamentoField;
        
        private string nuContratoField;
        
        private string nuCartaoPostagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string servico
        {
            get
            {
                return this.servicoField;
            }
            set
            {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cepOrigem
        {
            get
            {
                return this.cepOrigemField;
            }
            set
            {
                this.cepOrigemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cepDestino
        {
            get
            {
                return this.cepDestinoField;
            }
            set
            {
                this.cepDestinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int prazoEntrega
        {
            get
            {
                return this.prazoEntregaField;
            }
            set
            {
                this.prazoEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dataPostagem
        {
            get
            {
                return this.dataPostagemField;
            }
            set
            {
                this.dataPostagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string dataPostagemCalculo
        {
            get
            {
                return this.dataPostagemCalculoField;
            }
            set
            {
                this.dataPostagemCalculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dataMaxEntrega
        {
            get
            {
                return this.dataMaxEntregaField;
            }
            set
            {
                this.dataMaxEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string postagemDH
        {
            get
            {
                return this.postagemDHField;
            }
            set
            {
                this.postagemDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dataUltimoEvento
        {
            get
            {
                return this.dataUltimoEventoField;
            }
            set
            {
                this.dataUltimoEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string codigoUltimoEvento
        {
            get
            {
                return this.codigoUltimoEventoField;
            }
            set
            {
                this.codigoUltimoEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tipoUltimoEvento
        {
            get
            {
                return this.tipoUltimoEventoField;
            }
            set
            {
                this.tipoUltimoEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string descricaoUltimoEvento
        {
            get
            {
                return this.descricaoUltimoEventoField;
            }
            set
            {
                this.descricaoUltimoEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string msgErro
        {
            get
            {
                return this.msgErroField;
            }
            set
            {
                this.msgErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string nuTicket
        {
            get
            {
                return this.nuTicketField;
            }
            set
            {
                this.nuTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string formaPagamento
        {
            get
            {
                return this.formaPagamentoField;
            }
            set
            {
                this.formaPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string valorPagamento
        {
            get
            {
                return this.valorPagamentoField;
            }
            set
            {
                this.valorPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string nuContrato
        {
            get
            {
                return this.nuContratoField;
            }
            set
            {
                this.nuContratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string nuCartaoPostagem
        {
            get
            {
                return this.nuCartaoPostagemField;
            }
            set
            {
                this.nuCartaoPostagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cResultadoObjeto
    {
        
        private cObjeto[] objetosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public cObjeto[] Objetos
        {
            get
            {
                return this.objetosField;
            }
            set
            {
                this.objetosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoPrazo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoPrazoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sDsSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string nVlPeso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int nCdFormato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal nVlComprimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal nVlAltura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal nVlLargura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal nVlDiametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string sCdMaoPropria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal nVlValorDeclarado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string sCdAvisoRecebimento;
        
        public CalcPrecoPrazoRequest()
        {
        }
        
        public CalcPrecoPrazoRequest(string nCdEmpresa, string sDsSenha, string nCdServico, string sCepOrigem, string sCepDestino, string nVlPeso, int nCdFormato, decimal nVlComprimento, decimal nVlAltura, decimal nVlLargura, decimal nVlDiametro, string sCdMaoPropria, decimal nVlValorDeclarado, string sCdAvisoRecebimento)
        {
            this.nCdEmpresa = nCdEmpresa;
            this.sDsSenha = sDsSenha;
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.nVlPeso = nVlPeso;
            this.nCdFormato = nCdFormato;
            this.nVlComprimento = nVlComprimento;
            this.nVlAltura = nVlAltura;
            this.nVlLargura = nVlLargura;
            this.nVlDiametro = nVlDiametro;
            this.sCdMaoPropria = sCdMaoPropria;
            this.nVlValorDeclarado = nVlValorDeclarado;
            this.sCdAvisoRecebimento = sCdAvisoRecebimento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoPrazoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoPrazoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrecoPrazoResult;
        
        public CalcPrecoPrazoResponse()
        {
        }
        
        public CalcPrecoPrazoResponse(ServiceReference1.cResultado CalcPrecoPrazoResult)
        {
            this.CalcPrecoPrazoResult = CalcPrecoPrazoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoPrazoData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoPrazoDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sDsSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string nVlPeso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int nCdFormato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal nVlComprimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal nVlAltura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal nVlLargura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal nVlDiametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string sCdMaoPropria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal nVlValorDeclarado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string sCdAvisoRecebimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string sDtCalculo;
        
        public CalcPrecoPrazoDataRequest()
        {
        }
        
        public CalcPrecoPrazoDataRequest(string nCdEmpresa, string sDsSenha, string nCdServico, string sCepOrigem, string sCepDestino, string nVlPeso, int nCdFormato, decimal nVlComprimento, decimal nVlAltura, decimal nVlLargura, decimal nVlDiametro, string sCdMaoPropria, decimal nVlValorDeclarado, string sCdAvisoRecebimento, string sDtCalculo)
        {
            this.nCdEmpresa = nCdEmpresa;
            this.sDsSenha = sDsSenha;
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.nVlPeso = nVlPeso;
            this.nCdFormato = nCdFormato;
            this.nVlComprimento = nVlComprimento;
            this.nVlAltura = nVlAltura;
            this.nVlLargura = nVlLargura;
            this.nVlDiametro = nVlDiametro;
            this.sCdMaoPropria = sCdMaoPropria;
            this.nVlValorDeclarado = nVlValorDeclarado;
            this.sCdAvisoRecebimento = sCdAvisoRecebimento;
            this.sDtCalculo = sDtCalculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoPrazoDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoPrazoDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrecoPrazoDataResult;
        
        public CalcPrecoPrazoDataResponse()
        {
        }
        
        public CalcPrecoPrazoDataResponse(ServiceReference1.cResultado CalcPrecoPrazoDataResult)
        {
            this.CalcPrecoPrazoDataResult = CalcPrecoPrazoDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoPrazoRestricao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoPrazoRestricaoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sDsSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string nVlPeso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int nCdFormato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal nVlComprimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal nVlAltura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal nVlLargura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal nVlDiametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string sCdMaoPropria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal nVlValorDeclarado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string sCdAvisoRecebimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string sDtCalculo;
        
        public CalcPrecoPrazoRestricaoRequest()
        {
        }
        
        public CalcPrecoPrazoRestricaoRequest(string nCdEmpresa, string sDsSenha, string nCdServico, string sCepOrigem, string sCepDestino, string nVlPeso, int nCdFormato, decimal nVlComprimento, decimal nVlAltura, decimal nVlLargura, decimal nVlDiametro, string sCdMaoPropria, decimal nVlValorDeclarado, string sCdAvisoRecebimento, string sDtCalculo)
        {
            this.nCdEmpresa = nCdEmpresa;
            this.sDsSenha = sDsSenha;
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.nVlPeso = nVlPeso;
            this.nCdFormato = nCdFormato;
            this.nVlComprimento = nVlComprimento;
            this.nVlAltura = nVlAltura;
            this.nVlLargura = nVlLargura;
            this.nVlDiametro = nVlDiametro;
            this.sCdMaoPropria = sCdMaoPropria;
            this.nVlValorDeclarado = nVlValorDeclarado;
            this.sCdAvisoRecebimento = sCdAvisoRecebimento;
            this.sDtCalculo = sDtCalculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoPrazoRestricaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoPrazoRestricaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrecoPrazoRestricaoResult;
        
        public CalcPrecoPrazoRestricaoResponse()
        {
        }
        
        public CalcPrecoPrazoRestricaoResponse(ServiceReference1.cResultado CalcPrecoPrazoRestricaoResult)
        {
            this.CalcPrecoPrazoRestricaoResult = CalcPrecoPrazoRestricaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPreco", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sDsSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string nVlPeso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int nCdFormato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal nVlComprimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal nVlAltura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal nVlLargura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal nVlDiametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string sCdMaoPropria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal nVlValorDeclarado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string sCdAvisoRecebimento;
        
        public CalcPrecoRequest()
        {
        }
        
        public CalcPrecoRequest(string nCdEmpresa, string sDsSenha, string nCdServico, string sCepOrigem, string sCepDestino, string nVlPeso, int nCdFormato, decimal nVlComprimento, decimal nVlAltura, decimal nVlLargura, decimal nVlDiametro, string sCdMaoPropria, decimal nVlValorDeclarado, string sCdAvisoRecebimento)
        {
            this.nCdEmpresa = nCdEmpresa;
            this.sDsSenha = sDsSenha;
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.nVlPeso = nVlPeso;
            this.nCdFormato = nCdFormato;
            this.nVlComprimento = nVlComprimento;
            this.nVlAltura = nVlAltura;
            this.nVlLargura = nVlLargura;
            this.nVlDiametro = nVlDiametro;
            this.sCdMaoPropria = sCdMaoPropria;
            this.nVlValorDeclarado = nVlValorDeclarado;
            this.sCdAvisoRecebimento = sCdAvisoRecebimento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrecoResult;
        
        public CalcPrecoResponse()
        {
        }
        
        public CalcPrecoResponse(ServiceReference1.cResultado CalcPrecoResult)
        {
            this.CalcPrecoResult = CalcPrecoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sDsSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string nVlPeso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int nCdFormato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal nVlComprimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal nVlAltura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal nVlLargura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal nVlDiametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string sCdMaoPropria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal nVlValorDeclarado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string sCdAvisoRecebimento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string sDtCalculo;
        
        public CalcPrecoDataRequest()
        {
        }
        
        public CalcPrecoDataRequest(string nCdEmpresa, string sDsSenha, string nCdServico, string sCepOrigem, string sCepDestino, string nVlPeso, int nCdFormato, decimal nVlComprimento, decimal nVlAltura, decimal nVlLargura, decimal nVlDiametro, string sCdMaoPropria, decimal nVlValorDeclarado, string sCdAvisoRecebimento, string sDtCalculo)
        {
            this.nCdEmpresa = nCdEmpresa;
            this.sDsSenha = sDsSenha;
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.nVlPeso = nVlPeso;
            this.nCdFormato = nCdFormato;
            this.nVlComprimento = nVlComprimento;
            this.nVlAltura = nVlAltura;
            this.nVlLargura = nVlLargura;
            this.nVlDiametro = nVlDiametro;
            this.sCdMaoPropria = sCdMaoPropria;
            this.nVlValorDeclarado = nVlValorDeclarado;
            this.sCdAvisoRecebimento = sCdAvisoRecebimento;
            this.sDtCalculo = sDtCalculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrecoDataResult;
        
        public CalcPrecoDataResponse()
        {
        }
        
        public CalcPrecoDataResponse(ServiceReference1.cResultado CalcPrecoDataResult)
        {
            this.CalcPrecoDataResult = CalcPrecoDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrazo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrazoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sCepDestino;
        
        public CalcPrazoRequest()
        {
        }
        
        public CalcPrazoRequest(string nCdServico, string sCepOrigem, string sCepDestino)
        {
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrazoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrazoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrazoResult;
        
        public CalcPrazoResponse()
        {
        }
        
        public CalcPrazoResponse(ServiceReference1.cResultado CalcPrazoResult)
        {
            this.CalcPrazoResult = CalcPrazoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrazoData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrazoDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sDtCalculo;
        
        public CalcPrazoDataRequest()
        {
        }
        
        public CalcPrazoDataRequest(string nCdServico, string sCepOrigem, string sCepDestino, string sDtCalculo)
        {
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.sDtCalculo = sDtCalculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrazoDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrazoDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrazoDataResult;
        
        public CalcPrazoDataResponse()
        {
        }
        
        public CalcPrazoDataResponse(ServiceReference1.cResultado CalcPrazoDataResult)
        {
            this.CalcPrazoDataResult = CalcPrazoDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrazoRestricao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrazoRestricaoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sDtCalculo;
        
        public CalcPrazoRestricaoRequest()
        {
        }
        
        public CalcPrazoRestricaoRequest(string nCdServico, string sCepOrigem, string sCepDestino, string sDtCalculo)
        {
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.sDtCalculo = sDtCalculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrazoRestricaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrazoRestricaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrazoRestricaoResult;
        
        public CalcPrazoRestricaoResponse()
        {
        }
        
        public CalcPrazoRestricaoResponse(ServiceReference1.cResultado CalcPrazoRestricaoResult)
        {
            this.CalcPrazoRestricaoResult = CalcPrazoRestricaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoFAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoFACRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string nVlPeso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strDataCalculo;
        
        public CalcPrecoFACRequest()
        {
        }
        
        public CalcPrecoFACRequest(string nCdServico, string nVlPeso, string strDataCalculo)
        {
            this.nCdServico = nCdServico;
            this.nVlPeso = nVlPeso;
            this.strDataCalculo = strDataCalculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcPrecoFACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcPrecoFACResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado CalcPrecoFACResult;
        
        public CalcPrecoFACResponse()
        {
        }
        
        public CalcPrecoFACResponse(ServiceReference1.cResultado CalcPrecoFACResult)
        {
            this.CalcPrecoFACResult = CalcPrecoFACResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcDataMaxima", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcDataMaximaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string codigoObjeto;
        
        public CalcDataMaximaRequest()
        {
        }
        
        public CalcDataMaximaRequest(string codigoObjeto)
        {
            this.codigoObjeto = codigoObjeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcDataMaximaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcDataMaximaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultadoObjeto CalcDataMaximaResult;
        
        public CalcDataMaximaResponse()
        {
        }
        
        public CalcDataMaximaResponse(ServiceReference1.cResultadoObjeto CalcDataMaximaResult)
        {
            this.CalcDataMaximaResult = CalcDataMaximaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaServicos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListaServicosRequest
    {
        
        public ListaServicosRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaServicosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListaServicosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultadoServicos ListaServicosResult;
        
        public ListaServicosResponse()
        {
        }
        
        public ListaServicosResponse(ServiceReference1.cResultadoServicos ListaServicosResult)
        {
            this.ListaServicosResult = ListaServicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaServicosSTAR", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListaServicosSTARRequest
    {
        
        public ListaServicosSTARRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaServicosSTARResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListaServicosSTARResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultadoServicos ListaServicosSTARResult;
        
        public ListaServicosSTARResponse()
        {
        }
        
        public ListaServicosSTARResponse(ServiceReference1.cResultadoServicos ListaServicosSTARResult)
        {
            this.ListaServicosSTARResult = ListaServicosSTARResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificaModal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificaModalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sCepDestino;
        
        public VerificaModalRequest()
        {
        }
        
        public VerificaModalRequest(string nCdServico, string sCepOrigem, string sCepDestino)
        {
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificaModalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificaModalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultadoModal VerificaModalResult;
        
        public VerificaModalResponse()
        {
        }
        
        public VerificaModalResponse(ServiceReference1.cResultadoModal VerificaModalResult)
        {
            this.VerificaModalResult = VerificaModalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getVersaoRequest
    {
        
        public getVersaoRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getVersaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.versao getVersaoResult;
        
        public getVersaoResponse()
        {
        }
        
        public getVersaoResponse(ServiceReference1.versao getVersaoResult)
        {
            this.getVersaoResult = getVersaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcPrazoNovo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class calcPrazoNovoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nCdServico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sCepOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sCepDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sDtCalculo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strVerificaRestricao;
        
        public calcPrazoNovoRequest()
        {
        }
        
        public calcPrazoNovoRequest(string nCdServico, string sCepOrigem, string sCepDestino, string sDtCalculo, string strVerificaRestricao)
        {
            this.nCdServico = nCdServico;
            this.sCepOrigem = sCepOrigem;
            this.sCepDestino = sCepDestino;
            this.sDtCalculo = sDtCalculo;
            this.strVerificaRestricao = strVerificaRestricao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcPrazoNovoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class calcPrazoNovoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.cResultado calcPrazoNovoResult;
        
        public calcPrazoNovoResponse()
        {
        }
        
        public calcPrazoNovoResponse(ServiceReference1.cResultado calcPrazoNovoResult)
        {
            this.calcPrazoNovoResult = calcPrazoNovoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface CalcPrecoPrazoWSSoapChannel : ServiceReference1.CalcPrecoPrazoWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class CalcPrecoPrazoWSSoapClient : System.ServiceModel.ClientBase<ServiceReference1.CalcPrecoPrazoWSSoap>, ServiceReference1.CalcPrecoPrazoWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalcPrecoPrazoWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CalcPrecoPrazoWSSoapClient.GetBindingForEndpoint(endpointConfiguration), CalcPrecoPrazoWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalcPrecoPrazoWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalcPrecoPrazoWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalcPrecoPrazoWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalcPrecoPrazoWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalcPrecoPrazoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.CalcPrecoPrazoResponse CalcPrecoPrazo(ServiceReference1.CalcPrecoPrazoRequest request)
        {
            return base.Channel.CalcPrecoPrazo(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrecoPrazoResponse> CalcPrecoPrazoAsync(ServiceReference1.CalcPrecoPrazoRequest request)
        {
            return base.Channel.CalcPrecoPrazoAsync(request);
        }
        
        public ServiceReference1.CalcPrecoPrazoDataResponse CalcPrecoPrazoData(ServiceReference1.CalcPrecoPrazoDataRequest request)
        {
            return base.Channel.CalcPrecoPrazoData(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrecoPrazoDataResponse> CalcPrecoPrazoDataAsync(ServiceReference1.CalcPrecoPrazoDataRequest request)
        {
            return base.Channel.CalcPrecoPrazoDataAsync(request);
        }
        
        public ServiceReference1.CalcPrecoPrazoRestricaoResponse CalcPrecoPrazoRestricao(ServiceReference1.CalcPrecoPrazoRestricaoRequest request)
        {
            return base.Channel.CalcPrecoPrazoRestricao(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrecoPrazoRestricaoResponse> CalcPrecoPrazoRestricaoAsync(ServiceReference1.CalcPrecoPrazoRestricaoRequest request)
        {
            return base.Channel.CalcPrecoPrazoRestricaoAsync(request);
        }
        
        public ServiceReference1.CalcPrecoResponse CalcPreco(ServiceReference1.CalcPrecoRequest request)
        {
            return base.Channel.CalcPreco(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrecoResponse> CalcPrecoAsync(ServiceReference1.CalcPrecoRequest request)
        {
            return base.Channel.CalcPrecoAsync(request);
        }
        
        public ServiceReference1.CalcPrecoDataResponse CalcPrecoData(ServiceReference1.CalcPrecoDataRequest request)
        {
            return base.Channel.CalcPrecoData(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrecoDataResponse> CalcPrecoDataAsync(ServiceReference1.CalcPrecoDataRequest request)
        {
            return base.Channel.CalcPrecoDataAsync(request);
        }
        
        public ServiceReference1.CalcPrazoResponse CalcPrazo(ServiceReference1.CalcPrazoRequest request)
        {
            return base.Channel.CalcPrazo(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrazoResponse> CalcPrazoAsync(ServiceReference1.CalcPrazoRequest request)
        {
            return base.Channel.CalcPrazoAsync(request);
        }
        
        public ServiceReference1.CalcPrazoDataResponse CalcPrazoData(ServiceReference1.CalcPrazoDataRequest request)
        {
            return base.Channel.CalcPrazoData(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrazoDataResponse> CalcPrazoDataAsync(ServiceReference1.CalcPrazoDataRequest request)
        {
            return base.Channel.CalcPrazoDataAsync(request);
        }
        
        public ServiceReference1.CalcPrazoRestricaoResponse CalcPrazoRestricao(ServiceReference1.CalcPrazoRestricaoRequest request)
        {
            return base.Channel.CalcPrazoRestricao(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrazoRestricaoResponse> CalcPrazoRestricaoAsync(ServiceReference1.CalcPrazoRestricaoRequest request)
        {
            return base.Channel.CalcPrazoRestricaoAsync(request);
        }
        
        public ServiceReference1.CalcPrecoFACResponse CalcPrecoFAC(ServiceReference1.CalcPrecoFACRequest request)
        {
            return base.Channel.CalcPrecoFAC(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcPrecoFACResponse> CalcPrecoFACAsync(ServiceReference1.CalcPrecoFACRequest request)
        {
            return base.Channel.CalcPrecoFACAsync(request);
        }
        
        public ServiceReference1.CalcDataMaximaResponse CalcDataMaxima(ServiceReference1.CalcDataMaximaRequest request)
        {
            return base.Channel.CalcDataMaxima(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CalcDataMaximaResponse> CalcDataMaximaAsync(ServiceReference1.CalcDataMaximaRequest request)
        {
            return base.Channel.CalcDataMaximaAsync(request);
        }
        
        public ServiceReference1.ListaServicosResponse ListaServicos(ServiceReference1.ListaServicosRequest request)
        {
            return base.Channel.ListaServicos(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListaServicosResponse> ListaServicosAsync(ServiceReference1.ListaServicosRequest request)
        {
            return base.Channel.ListaServicosAsync(request);
        }
        
        public ServiceReference1.ListaServicosSTARResponse ListaServicosSTAR(ServiceReference1.ListaServicosSTARRequest request)
        {
            return base.Channel.ListaServicosSTAR(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListaServicosSTARResponse> ListaServicosSTARAsync(ServiceReference1.ListaServicosSTARRequest request)
        {
            return base.Channel.ListaServicosSTARAsync(request);
        }
        
        public ServiceReference1.VerificaModalResponse VerificaModal(ServiceReference1.VerificaModalRequest request)
        {
            return base.Channel.VerificaModal(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.VerificaModalResponse> VerificaModalAsync(ServiceReference1.VerificaModalRequest request)
        {
            return base.Channel.VerificaModalAsync(request);
        }
        
        public ServiceReference1.getVersaoResponse getVersao(ServiceReference1.getVersaoRequest request)
        {
            return base.Channel.getVersao(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getVersaoResponse> getVersaoAsync(ServiceReference1.getVersaoRequest request)
        {
            return base.Channel.getVersaoAsync(request);
        }
        
        public ServiceReference1.calcPrazoNovoResponse calcPrazoNovo(ServiceReference1.calcPrazoNovoRequest request)
        {
            return base.Channel.calcPrazoNovo(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.calcPrazoNovoResponse> calcPrazoNovoAsync(ServiceReference1.calcPrazoNovoRequest request)
        {
            return base.Channel.calcPrazoNovoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalcPrecoPrazoWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CalcPrecoPrazoWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalcPrecoPrazoWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.correios.com.br:8083/calculador/calcprecoprazo.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CalcPrecoPrazoWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.correios.com.br:8083/calculador/calcprecoprazo.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CalcPrecoPrazoWSSoap,
            
            CalcPrecoPrazoWSSoap12,
        }
    }
}
